spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 改成你本地的数据库名
    url: jdbc:mysql://localhost:3306/Swallows?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    # 改成你本地的数据库账号密码
    username: root
    password: 123
  # jpa配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
  mvc:
    # 处理前端访问的API路径不存在 令它抛出异常
    throw-exception-if-no-handler-found: true
  # 静态资源管理
  resources:
    # 上传文件临时存放位置
    static-locations: classpath:/static/, file:${web.upload_path}
    # 令它抛出异常
    add-mappings: false
  # 配置文件上传
  servlet:
    multipart:
      # 文件上传是否开启
      enabled: true
      # 单个数据的大小
      max-file-size: 1MB
      # 总数据的大小
      max-request-size: 10MB
  # json处理
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

# 改成你本地的文件上传路径
web.upload_path: D:\springboot开发\雏雁项目\WeSwallows\src\main\resources\static\images

# 项目运行端口
server:
  port: 8080

# 日志
logging:
  level:
    root: info
    com.lrm: debug
  file: log/blog.log
